### ISSUE TITLE
Vanilla JS version

### ISSUE THREAD

**Issue by Jab2870** [yongzhenlow/email-autocomplete#16]
Hi, thanks for making this. Do you have any interest in removing the requirement for jQuery?

**Comment by noc2spam** [comment]
I have rewritten this library in vanillaJS. You can refer to that if needed..

https://github.com/noc2spam/JSEmailAutoComplete

**Comment by yongzhenlow** [comment]
Missed this out, thanks @noc2spam for helping out!
